name: data-infra-part3

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1-python3.11
  environment:
    &airflow-common-env
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DATABASE_USERNAME:-admin}:${AIRFLOW_DATABASE_PASSWORD:-password}@airflow-postgres:${AIRFLOW_DATABASE_PORT:-5432}/${AIRFLOW_DATABASE_NAME:-airflow}"
    AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW_FERNET_KEY}"
    _AIRFLOW_WWW_USER_USERNAME: "${AIRFLOW_WWW_USER_USERNAME:-admin}"
    _AIRFLOW_WWW_USER_PASSWORD: "${AIRFLOW_WWW_USER_PASSWORD:-password}"
    _AIRFLOW_WWW_USER_ROLE: "Admin"
    _AIRFLOW_WWW_USER_FIRSTNAME: "${AIRFLOW_WWW_USER_FIRSTNAME:-firstname}"
    _AIRFLOW_WWW_USER_LASTNAME: "${AIRFLOW_WWW_USER_LASTNAME:-lastname}"
    _AIRFLOW_WWW_USER_EMAIL: "${AIRFLOW_WWW_USER_EMAIL:-admin@example.com}"
    AIRFLOW_VAR_TIMESCALE_READONLY_USERNAME: "${TIMESCALE_READONLY_USERNAME:-user}"
    AIRFLOW_VAR_TIMESCALE_READONLY_PASSWORD: "${TIMESCALE_READONLY_PASSWORD:-password}"
    AIRFLOW_VAR_TIMESCALE_CONN_ID_ADMIN: "${TIMESCALE_CONN_ID_ADMIN:-timescale_conn_admin}"
    AIRFLOW_VAR_TIMESCALE_CONN_ID_READONLY: "${TIMESCALE_CONN_ID_READONLY:-timescale_conn_readonly}"
    AIRFLOW_VAR_ROOT_PROJ_NAME: "${ROOT_PROJ_NAME:-part3}"
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS: "false"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__LOGGING__LOGGING_LEVEL: "DEBUG"
    AIRFLOW_VAR_BINANCE_API_KEY: "${BINANCE_API_KEY}"
  user: ${AIRFLOW_UID:-50000}
  depends_on:
    airflow-postgres:
      condition: service_healthy
  volumes:
    - ${AIRFLOW_PROJ_DIR:-../pipecraft}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-../pipecraft}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-../pipecraft}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-../pipecraft}/plugins:/opt/airflow/plugins

services:

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "${AIRFLOW_WWW_PORT:-8080}:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always

  airflow-postgres:
    container_name: airflow-postgres
    image: postgres:13
    environment:
      POSTGRES_DB: "${AIRFLOW_DATABASE_NAME:-airflow}"
      POSTGRES_USER: "${AIRFLOW_DATABASE_USERNAME:-admin}"
      POSTGRES_PASSWORD: "${AIRFLOW_DATABASE_PASSWORD:-password}"
    ports:
      - "${AIRFLOW_DATABASE_PORT:-5432}:5432"
    volumes:
      - ../.storage/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${AIRFLOW_DATABASE_NAME:-airflow}", "-U", "${AIRFLOW_DATABASE_USERNAME:-admin}" ]
      interval: 5s
      retries: 2
      start_period: 3s
    restart: unless-stopped

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: true
    restart: no
    entrypoint: /opt/airflow/scripts/entry_init.sh
    volumes:
      - ${AIRFLOW_PROJ_DIR:-../pipecraft}/scripts:/opt/airflow/scripts

  timescale:
    container_name: timescale
    image:  timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: "${TIMESCALE_DATABASE_NAME:-timescale}"
      POSTGRES_USER: "${TIMESCALE_ADMIN_USERNAME:-admin}"
      POSTGRES_PASSWORD: "${TIMESCALE_ADMIN_PASSWORD:-password}"
    ports:
      - "${TIMESCALE_PORT:-5433}:5432"
    volumes:
      - ../.storage/timescale:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${TIMESCALE_DATABASE_NAME:-timescale}", "-U", "${TIMESCALE_ADMIN_USERNAME:-admin}" ]
      interval: 5s
      retries: 2
      start_period: 3s
    restart: unless-stopped
